### ISSUE TITLE
nbgrader config change to ExecutePreprocessor.timeout seems to be ignored

### ISSUE THREAD

**Issue by davidpwilliamson** [jupyter/nbgrader#1004]
### Operating system

Windows 10

### `nbgrader --version`

0.5.4

### `jupyterhub --version` (if used with JupyterHub)

NA

### `jupyter notebook --version` 

5.0.0

### Expected behavior

I've created a lab exercise in which students read files and run code on them; I created a bunch of hidden tests to check their output.  

### Actual behavior

When I try to validate the code, I get a 'Keyboard Interrupt', which appears to be a timeout error in validating the code.  I've tried to set the configuration file to change 
c.ExecutePreprocessor.timeout to None or 300, but this change in parameter seems to be ignored for several cells.  When I start the notebook with the --debug option on, I get errors during the validate of the following sort: 
[E 16:30:43.087 NotebookApp] Timeout waiting for execute reply (30s).
even though I've set the parameter value to None or 300, suggesting that the default has overridden my change in parameter.  I've checked via the logs that the code is reading the config file from the correct file.

**Comment by jhamrick** [comment]
Confirmed, though this seems to only be a problem when running autograde through the formgrader interface, as far as I can tell (was that the case for you too, or were you running `nbgrader autograde` through the command line?)

**Comment by rokinmaharjan** [comment]
@jhamrick Any updates on this?

**Comment by saurssauravjs** [comment]
@rokinmaharjan , Its issue i have been facing since last week. Hope to see some updates in it!

**Comment by jhamrick** [comment]
I believe this should have been fixed by #1075

**Comment by heathermiller** [comment]
I'm still having this problem, exactly the same as described above. Like @davidpwilliamson above, I've run `jupyter notebook` with the --debug option on, and I've verified that the nbgrader_config.py file is being read, both in the root course directory as well as in the notebook directory. 

When validating the notebook, I consistently get errors of the form:

```
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
```

Despite the fact that `c.ExecutePreprocessor.timeout = 60` in the nbgrader_config.py file in my notebook directory.

**Comment by rkdarst** [comment]
Yeah... I've tried many times to make it work, but somehow it just doesn't.  I eventually gave up and left my hack of dynamically editing source files after spawn...

Just so you know it's not just you.  But I'm at the limits of my debugging here...

**Comment by RonaldEnsing** [comment]
I am running into the same issue with `nbgrader version 0.6.2` on Linux. Running `nbgrader validate <my_assignment>.ipynb` I get the following output after -+120 seconds, even though I set `c.ExecutePreprocessor.timeout = 600`:
```
[ValidateApp | ERROR] Timeout waiting for execute reply (30s).
[ValidateApp | ERROR] Interrupting kernel
Success! Your notebook passes all the tests.
```

**Comment by AbeHandler** [comment]
+1 yeah I am having the same issue described on this thread
